name: Terraform Deploy Strapi ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  DOCKER_IMAGE: shunnualisha8980/strapi-app
  ECS_CLUSTER: strapi-cluster
  ECS_SERVICE: strapi-service
  CODEDEPLOY_APP: strapi-codedeploy
  CODEDEPLOY_GROUP: strapi-deployment-group

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image to Docker Hub
        working-directory: ./my-strapi-app
        run: |
          docker build -t $DOCKER_IMAGE:${{ github.sha }} .
          docker push $DOCKER_IMAGE:${{ github.sha }}

      - name: Make scripts executable
        run: chmod +x task12.terraform/scripts/*.sh

      - name: Zip AppSpec and scripts
        run: |
          mkdir -p zipped
          zip -r zipped/deploy-strapi.zip task12.terraform/deploy/appspec.yml task12.terraform/scripts/

      - name: Upload AppSpec to S3
        run: |
          aws s3 cp zipped/deploy-strapi.zip s3://strapi786/deploy-strapi.zip

      - name: Terraform Init
        run: terraform init
        working-directory: ./task12.terraform

      - name: Terraform Plan
        run: terraform plan -var "image_tag=${{ github.sha }}"
        working-directory: ./task12.terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image_tag=${{ github.sha }}"
        working-directory: ./task12.terraform

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP \
            --deployment-group-name $CODEDEPLOY_GROUP \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --description "GitHub Actions deployment" \
            --s3-location bucket=strapi786,bundleType=zip,key=deploy-strapi.zip
